### ISSUE TITLE
2.9.3 related error during site generation

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#524]
`bundle exec jekyll serve` gives:

```
jekyll 3.3.0 | Error:  Is a directory @ rb_sysopen - /Users/tisue/scala-lang/_site/news/2.9.3
```

I don't see the same error at e.g. https://scala-webapps.epfl.ch/jenkins/view/All/job/production_scala-lang.org-builder/549/console . no idea what's up

**Comment by SethTisue** [comment]
with `serve -t`:

```
Errno::EISDIR: Is a directory @ rb_sysopen - /Users/tisue/scala-lang/_site/news/2.9.3
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/document.rb:231:in `write'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/document.rb:231:in `write'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:212:in `block in write'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:333:in `block (2 levels) in each_site_file'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:332:in `each'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:332:in `block in each_site_file'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:331:in `each'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:331:in `each_site_file'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:211:in `write'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:71:in `process'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/command.rb:26:in `process_site'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:63:in `build'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:34:in `process'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/gems/jekyll-3.3.0/exe/jekyll:13:in `<top (required)>'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/bin/jekyll:23:in `load'
  /Users/tisue/scala-lang/bundle-vendor/bundle/ruby/2.2.0/bin/jekyll:23:in `<top (required)>'
```

**Comment by SethTisue** [comment]
false alarm, problem went away after blowing away `_site`
